config/routes.rb
Rails.application.routes.draw do
  root "home_page#home"

  devise_for :users, skip: %i(sessions registrations)
  as :user do
    get "/login", to: "users/sessions#new", as: :new_user_session
    post "/login", to: "users/sessions#create", as: :user_session
    delete "/logout", to: "devise/sessions#destroy", as: :destroy_user_session

    get "/signup", to: "users/registrations#new", as: :new_user_registration
    post "/signup", to: "devise/registrations#create", as: :user_registration
  end

  get "/history", to: "histories#index"

  resources :tours, only: %i(index show)
  resources :users, only: :show
  resources :categories, only: :show
  resources :reviews, only: :create
  resources :ratings, only: %i(create update)
  resources :bookings, only: %i(new create)

  namespace :admin do
    root "dashboard#index"
    resources :bookings, only: %i(index show update)
    resources :categories, except: %i(new edit update)
    resources :tours do
      resources :description_details, except: %i(index show)
    end
  end
end

app/views/share/_alert.html.erb
<% flash.each do |msg_type, msg| %>
  <div class="alert alert-<%= msg_type %>">
    <a href="#" data-dismiss="alert" class="close">x</a>
    <ul>
      <li>
        <%= msg %>
      </li>
    </ul>
  </div>
<% end %>

app/views/share/_banner.html.erb
<div id="banner">
    <%= image_tag "img_bg_3.jpg", class: "img-responsive" %>
    <div class="tour-title">
      <h2><%= @tour.name %></h2>
    </div>
</div>

app/views/share/_error_messages_detail.html.erb
<% if @description_detail.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= pluralize @description_detail.errors.count, t(".error") %>.
    </div>
    <ul>
    <% @description_detail.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/share/_error_messages_tour.html.erb
<% if @tour.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= pluralize @tour.errors.count, t("share.error_messages_detail.error") %>.
    </div>
    <ul>
    <% @tour.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/share/_footer.html.erb
<div class="container-fluid foot-sign-up">
  <div class="overlay"></div>
  <div class="content container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3 text-center">
        <h4><%= t ".signup_now" %></h4>
        <%= link_to t("share.top_navigation.signup"), new_user_registration_path,
          class: "btn btn-default btn-yellow" %>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid foot-info">
  <div class="copyright">
    <p><%= t ".copyright_html" %></p>
  </div>
</div>

app/views/share/_search.html.erb
<div id="search" class="container-fluid">
  <div class="form-inline search-form">
    <div class="form-group">
      <%= search_form_for @search_tours do |f| %>
        <%= f.search_field :name_cont, class: "form-control", placeholder: t(".tour_name") %>
        <%= f.search_field :itinerary_cont, class: "form-control", placeholder: t(".desti") %>
        <%= submit_tag t(".search"), name: nil, class: "btn btn-default btn-search" %>
      <% end %>
    </div>
  </div>
</div>

app/views/share/_slider.html.erb
<div id="slider" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#slider" data-slide-to="0" class="active"></li>
    <li data-target="#slider" data-slide-to="1"></li>
    <li data-target="#slider" data-slide-to="2"></li>
  </ol>

  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag "img_bg_1.jpg" %>
      <div class="carousel-caption">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit.
      </div>
    </div>
    <div class="item">
      <%= image_tag "img_bg_2.jpg" %>
      <div class="carousel-caption">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit.
      </div>
    </div>
    <div class="item">
      <%= image_tag "img_bg_3.jpg" %>
      <div class="carousel-caption">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit.
      </div>
    </div>
  </div>

  <a class="left carousel-control" href="#slider" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#slider" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/share/_submenu.html.erb
<% if category.childs.any? %>
  <li class="dropdown">
    <%= link_to category, class: "dropdown-toggle", onclick: "menuItemClick(this)", data: {toggle: "dropdown", hover: "dropdown"} do %>
      <%= category.name %><span class="caret"></span>
    <% end %>
    <ul class="dropdown-menu">
      <%= render partial: "share/submenu", collection: category.childs, as: :category %>
    </ul>
  </li>
<% else %>
  <li><%= link_to category.name, category %></li>
<% end %>

app/views/share/_top_navigation.html.erb
<nav id="top-nav" class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to t(".tour"), root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav main-menu">
        <li><%= link_to t(".home"), root_path %></a></li>
        <%= draw_categories(@super_categories).html_safe %>
        <li><%= link_to t(".about"), "#" %></li>
        <li><%= link_to t(".contact"), "#" %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% unless user_signed_in? %>
          <li><%= link_to t(".login"), new_user_session_path %></li>
          <li><%= link_to t(".signup"), new_user_registration_path %></li>
        <% else %>
          <li>
            <span class="greeting"><%= t ".greeting", name: current_user.name %></span></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= t ".account" %><span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile"), current_user %></li>
              <li><%= link_to t(".booking_history"), history_path %></li>
              <li class="divider"></li>
              <li><%= link_to t(".logout"), destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>