config/routes.rb
Rails.application.routes.draw do
  root "home_page#home"

  devise_for :users, skip: %i(sessions registrations)
  as :user do
    get "/login", to: "users/sessions#new", as: :new_user_session
    post "/login", to: "users/sessions#create", as: :user_session
    delete "/logout", to: "devise/sessions#destroy", as: :destroy_user_session

    get "/signup", to: "users/registrations#new", as: :new_user_registration
    post "/signup", to: "devise/registrations#create", as: :user_registration
  end

  get "/history", to: "histories#index"

  resources :tours, only: %i(index show)
  resources :users, only: :show
  resources :categories, only: :show
  resources :reviews, only: :create
  resources :ratings, only: %i(create update)
  resources :bookings, only: %i(new create)

  namespace :admin do
    root "dashboard#index"
    resources :bookings, only: %i(index show update)
    resources :categories, except: %i(new edit update)
    resources :tours do
      resources :description_details, except: %i(index show)
    end
  end
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def home
    @tours = Tour.without_deleted.name_sort.limit Settings.tour.limit_list
    @newest_tours = Tour.without_deleted.newest_tour.limit Settings.tour.limit_list
    @recommended_tours = Tour.without_deleted.recommended_tour
      .limit Settings.tour.recommended_limit
  end
end

app/helpers/home_page_helper.rb
module HomePageHelper
  def draw_categories categories
    html = ""
    categories.each do |category|
      check_to_show_category(category, html)
    end
    html
  end

  def draw_subcategories category
    html = "<ul class='dropdown-menu multi-level'>"
    category.childs.each do |c|
      check_to_show_subcategory(c, html)
    end
    html << "</ul>"
    html
  end

  def has_child? category
    category.childs.any?
  end

  def check_to_show_category category, html
    if has_child?(category)
      html << "<li>"
      html << "<a href='#' class='dropdown-toggle' data-toggle='dropdown'>
        #{category.name}<span class='caret'></span></a>"
      html << draw_subcategories(category)
      html << "</li>"
    else
      html << "<li><a href='#'>#{category.name}</a></li>"
    end
  end

  def check_to_show_subcategory category, html
    if has_child?(category)
      html << "<li class='dropdown-submenu'>"
      html << "<a href='#' class='dropdown-toggle' data-toggle='dropdown'>
        #{category.name}</a>"
      html << draw_subcategories(category)
      html << "</li>"
    else
      html << "<li><a href='#'>#{category.name}</a></li>"
    end
  end
end

app/views/home_page/home.html.erb
<% content_for :head_decor do %>
  <%= render "share/slider" %>
<% end %>
<div class="container-fluid">
  <div class="tours popular-tour">
    <div class="container">
      <h2><%= t ".newest_tours" %></h2>
      <p><%= t ".newest_description" %></p>
      <div class="row">
        <%= render @newest_tours %>
        <div class="col-md-12">
          <%= link_to t(".seemore"), tours_path(filter: Settings.tour.param_newest) %>
        </div>
      </div>
    </div>
    <div class="container">
      <h2><%= t ".recommended_tours" %></h2>
      <p><%= t ".recommended_description" %></p>
      <div class="row">
        <%= render @recommended_tours %>
      </div>
    </div>
    <div class="container">
      <h2><%= t ".popular_tours" %></h2>
      <p><%= t ".popular_description" %></p>
      <div class="row">
        <%= render @tours %>
        <div class="col-md-12">
          <a href="#"><%= t ".seemore" %></a>
        </div>
      </div>
    </div>
  </div>
</div>