config/routes.rb
Rails.application.routes.draw do
  root "home_page#home"

  devise_for :users, skip: %i(sessions registrations)
  as :user do
    get "/login", to: "users/sessions#new", as: :new_user_session
    post "/login", to: "users/sessions#create", as: :user_session
    delete "/logout", to: "devise/sessions#destroy", as: :destroy_user_session

    get "/signup", to: "users/registrations#new", as: :new_user_registration
    post "/signup", to: "devise/registrations#create", as: :user_registration
  end

  get "/history", to: "histories#index"

  resources :tours, only: %i(index show)
  resources :users, only: :show
  resources :categories, only: :show
  resources :reviews, only: :create
  resources :ratings, only: %i(create update)
  resources :bookings, only: %i(new create)

  namespace :admin do
    root "dashboard#index"
    resources :bookings, only: %i(index show update)
    resources :categories, except: %i(new edit update)
    resources :tours do
      resources :description_details, except: %i(index show)
    end
  end
end

app/models/tour.rb
class Tour < ApplicationRecord
  belongs_to :category
  has_many :description_details, dependent: :destroy
  has_many :reviews
  has_many :ratings

  mount_uploader :image, ImageUploader

  validates :name, presence: true, uniqueness: true
  validates :itinerary, presence: true
  validates :short_description, presence: true, length: {maximum: Settings.tour.length_short_des}
  validates :content, presence: true
  validates :image, presence: true
  validate :image_size

  acts_as_paranoid without_default_scope: true

  scope :name_sort, ->{order "name asc"}
  scope :newest_tour, ->{order "created_at desc"}
  scope :recommended_tour, ->{order "rating desc"}
  scope :select_tours_by_category, ->(category_id){where category_id: category_id}
  scope :except_id, ->(id){where.not id: id}
  scope :check_pending_booking, ->(id, status){where("tours.id = ? AND bookings.status = ?", id, status)}

  def update_rating_average
    rating_average = ratings.any? ? ratings.average(:point).to_i : 0
    self.update_attribute :rating, rating_average
  end

  def has_pending_booking? id
    Tour.joins(description_details: :bookings).
      check_pending_booking(id, Booking.statuses[:pending]).any?
  end

  private

  def image_size
    return errors.add :image, I18n.t(".error_image_size") if image.size > 5.megabytes
  end
end

app/controllers/admin/tours_controller.rb
module Admin
  class ToursController < BaseController
    before_action :load_tour, except: %i(index new create)
    before_action :load_categories, except: %i(index show destroy)

    def index
      @tours = @search_tours.result.newest_tour
        .paginate page: params[:page], per_page: Settings.tour.per_page
    end

    def show
      @description_details = @tour.description_details.without_deleted
    end

    def new
      @tour = Tour.new
    end

    def create
      @tour = Tour.new tour_params
      if @tour.save
        flash[:success] = t ".creat_success"
        redirect_to admin_tours_url
      else
        render :new
      end
    end

    def edit; end

    def update
      if @tour.update_attributes tour_params
        flash[:success] = t ".tour_updated"
        redirect_to admin_tour_url @tour
      else
        render :edit
      end
    end

    def destroy
      if @tour.has_pending_booking? @tour.id
        flash[:danger] = t ".error_delete"
      else
        @tour.destroy
        flash[:success] = t ".delete_success"
      end
      redirect_to admin_tours_url
    end

    private

    def tour_params
      params.require(:tour).permit :name, :itinerary, :content, :short_description, :category_id, :image
    end

    def load_tour
      @tour = Tour.without_deleted.find_by id: params[:id]
      return if @tour
      flash[:danger] = t ".error_id_tour"
      redirect_to admin_tours_url
    end

    def load_categories
      @categories = Category.all
    end
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :load_tour, only: :show

  def show
    @description_details = @tour.description_details.without_deleted.hidden_expired_detail
    @tours = Tour.without_deleted.select_tours_by_category(@tour.category_id)
      .except_id params[:id]
    able_to_review_and_rating
  end

  def index
    if params[:filter] == Settings.tour.param_newest
      @tours = Tour.without_deleted.newest_tour
        .paginate page: params[:page], per_page: Settings.tour.per_page
    else
      @tours = @search_tours.result
        .paginate(page: params[:page], per_page: Settings.tour.per_page)
    end
  end

  private

  def load_tour
    @tour = Tour.without_deleted.find_by id: params[:id]
    return if @tour
    flash[:danger] = t ".error_noti"
    redirect_to root_url
  end

  def able_to_review_and_rating
    return unless user_signed_in?
    @review = Review.new
    @rating = current_user.ratings.find_by tour_id: @tour.id
    @rating ||= Rating.new
  end
end

app/views/admin/tours/_form_tour.html.erb
 <%= form_for [:admin, @tour] do |f| %>
  <%= render "share/error_messages_tour" %>
  <fieldset>
    <div class="form-group">
      <%= f.label :name, t(".name") %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :itinerary, t(".itinerary") %>
      <%= f.text_field :itinerary, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :short_description, t(".short_description") %>
      <%= f.text_field :short_description, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :content, t(".content") %>
      <%= f.text_area :content, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :image, t(".image"), class: "col-md-2 control-label" %>
      <%= f.file_field :image, accept: "image/jpeg, image/gif, image/png" %>
      <div class="col-md-10">
        <p class="help-block">
          <%= t ".help_block" %>
        </p>
      </div>
    </div>
    <%= f.label :category, t(".category"), class: "col-md-2 control-label" %>
      <div class="col-md-10">
        <%= f.select :category_id, options_for_select(@categories.collect{|c| [c.name, c.id]}) %>
      </div>
  </fieldset>
  <%= f.submit t(".submit"), class: "btn btn-primary" %>
<% end %>

app/views/admin/tours/_tour.html.erb
<tr>
  <td><%= tour.id %></td>
  <td><%= tour.name %></td>
  <td><%= tour.short_description %></td>
  <td><%= tour.category.name %></td>
  <td><%= tour.itinerary %></td>
  <th><%= image_tag tour.image.thumb.url if tour.image? %>
  </th>
  <td>
    <%= link_to t(".view"), admin_tour_path(tour), class: "btn btn-info" %>
    <%= link_to t(".edit"), edit_admin_tour_path(tour), class: "btn btn-default" %>
    <%= link_to t(".delete"), admin_tour_path(tour),
      method: :delete, data: { confirm: t(".make_sure") }, class: "btn btn-default" %>
  </td>
</tr>

app/views/admin/tours/edit.html.erb
<div class="panel-title">
  <h3><%= t ".edit_tour" %></h3>
</div>
<div class="content-box-large">
  <div class="panel-body">
    <%= render "form_tour" %>
  </div>
</div>

app/views/admin/tours/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="content-box-large">
      <div class="panel-heading">
        <div class="panel-title">
          <h3><%= t ".tours_list" %></h3>
        </div>
        <%= link_to t(".create_tour"), new_admin_tour_path, class: "btn btn-primary pull-right" %>
        <div class="form-inline search-form">
          <div class="form-group">
            <%= search_form_for @search_tours, url: admin_tours_path, method: :get do |f| %>
              <%= f.search_field :id_eq, class: "form-control", placeholder: t(".id") %>
              <%= f.search_field :name_cont, class: "form-control", placeholder: t(".tour_name") %>
              <%= f.search_field :category_name_cont, class: "form-control", placeholder: t(".category_tour") %>
              <%= f.search_field :itinerary_cont, class: "form-control", placeholder: t(".itinerary") %>
              <%= submit_tag t(".search"), name: nil, class: "btn btn-default btn-search" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="panel-body">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>#</th>
              <th><%= t ".tour_name" %></th>
              <th><%= t ".short_description" %></th>
              <th><%= t ".category_tour" %></th>
              <th><%= t ".itinerary" %></th>
              <th><%= t ".image" %></th>
              <th><%= t ".action" %></th>
            </tr>
          </thead>
          <tbody>
            <%= render @tours %>
          </tbody>
        </table>
        <%= will_paginate @tours %>
      </div>
    </div>
  </div>
</div>

app/views/admin/tours/new.html.erb
<div class="panel-title">
  <h3><%= t ".create_tour" %></h3>
</div>
<div class="content-box-large">
  <div class="panel-body">
    <%= render "form_tour" %>
  </div>
</div>

app/views/admin/tours/show.html.erb
<div class="content-box-large">
  <div class="panel-heading">
    <div class="page-header show-booking">
      <h3><%= t ".tour_detail" %></h3>
    </div>
    <%= link_to t(".create_detail"), new_admin_tour_description_detail_path(@tour), class: "btn btn-primary pull-right" %>
  </div>

  <div class="panel-body">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2"><%= t ".tour_no", no: @tour.id %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><b><%= t "admin.tours.index.tour_name" %></b></td>
          <td><%= @tour.name %></td>
        </tr>
        <tr>
          <td><b><%= t "admin.tours.index.short_description" %></b></td>
          <td><%= @tour.short_description %></td>
        </tr>
        <tr>
          <td><b><%= t "admin.tours.index.category_name" %></b></td>
          <td><%= @tour.category.name %></td>
        </tr>
        <tr>
          <td><b><%= t "admin.tours.index.itinerary" %></b></td>
          <td><%= @tour.itinerary %></td>
        </tr>
        <tr>
          <td><b><%= t ".content" %></b></td>
          <td><%= @tour.content %></td>
        </tr>
        <tr>
          <td><b><%= t ".rating" %></b></td>
          <td><%= @tour.rating %></td>
        </tr>
        <tr>
          <td><b><%= t "admin.tours.index.image" %></b></td>
          <td><%= image_tag @tour.image.thumb.url if @tour.image? %></td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="panel-body">
    <table class="table table-bordered">
      <%= render @description_details %>
    </table>
  </div>
</div>