config/routes.rb
Rails.application.routes.draw do
  root "home_page#home"

  devise_for :users, skip: %i(sessions registrations)
  as :user do
    get "/login", to: "users/sessions#new", as: :new_user_session
    post "/login", to: "users/sessions#create", as: :user_session
    delete "/logout", to: "devise/sessions#destroy", as: :destroy_user_session

    get "/signup", to: "users/registrations#new", as: :new_user_registration
    post "/signup", to: "devise/registrations#create", as: :user_registration
  end

  get "/history", to: "histories#index"

  resources :tours, only: %i(index show)
  resources :users, only: :show
  resources :categories, only: :show
  resources :reviews, only: :create
  resources :ratings, only: %i(create update)
  resources :bookings, only: %i(new create)

  namespace :admin do
    root "dashboard#index"
    resources :bookings, only: %i(index show update)
    resources :categories, except: %i(new edit update)
    resources :tours do
      resources :description_details, except: %i(index show)
    end
  end
end

app/views/admin/share/_header.html.erb
<div class="header">
     <div class="container">
        <div class="row">
           <div class="col-md-5">
              <div class="logo">
                 <h1><%= link_to t(".admin_panel"), admin_root_path %></h1>
              </div>
           </div>

           <div class="col-md-2 col-md-offset-5">
              <div class="navbar navbar-inverse" role="banner">
                  <nav class="collapse navbar-collapse bs-navbar-collapse navbar-right" role="navigation">
                    <ul class="nav navbar-nav">
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                          <%= t ".my_account" %> <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu animated fadeInUp">
                          <li><a href="#"><%= t ".profile" %></a></li>
                          <li><%= link_to t(".goto_tour_page"), root_path %></li>
                          <li><%= link_to t(".logout"),
                            destroy_user_session_path, method: :delete %></li>
                        </ul>
                      </li>
                    </ul>
                  </nav>
              </div>
           </div>
        </div>
     </div>
</div>

app/views/admin/share/_sidebar.html.erb
<div class="sidebar content-box" style="display: block;">
  <ul class="nav">
    <li>
      <%= link_to admin_root_path do %>
        <i class="glyphicon glyphicon-home"></i><%= t ".dashboard" %>
      <% end %>
    </li>
    <li>
      <%= link_to admin_bookings_path do%>
        <i class="glyphicon glyphicon-list"></i><%= t ".bookings" %>
      <% end %>
    </li>
    <li>
      <%= link_to admin_tours_path do%>
        <i class="glyphicon glyphicon-list"></i><%= t ".tours" %>
      <% end %>
    </li>
    <li>
      <a href="#"><i class="glyphicon glyphicon-record"></i><%= t ".users" %></a>
    </li>
    <li>
      <%= link_to admin_categories_path do %>
        <i class="glyphicon glyphicon-pencil"></i><%= t ".categories" %>
      <% end %>
    </li>
    <li>
      <a href="#"><i class="glyphicon glyphicon-stats"></i><%= t ".statistics" %></a>
    </li>
  </ul>
</div>